name: cherrytree
base: core18
version: 0.99.0
summary: Hierarchical note taking application
description: |
  A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single XML or SQLite file. The project home page is giuspen.com/cherrytree.
grade: stable
confinement: strict

slots:
  cherrytree:
    interface: dbus
    bus: session
    name: com.giuspen.cherrytree

apps:
  cherrytree:
    command: desktop-launch $SNAP/bin/cherrytree
    extensions: [gnome-3-34]
    plugs:
      - home
      - removable-media
    desktop: share/applications/cherrytree.desktop
    common-id: com.giuspen.cherrytree

parts:
  cherrytree:
    source: .
    source-subdir: future
    source-depth: 1
    plugin: cmake
    configflags: [
      "-DCMAKE_C_COMPILER=gcc-8",      # Required because cherrytree uses #include <filesystem>
      "-DCMAKE_CXX_COMPILER=g++-8",    # Required because cherrytree uses #include <filesystem>
      "-DPYTHON_EXEC=/usr/bin/python3" # Required so that /snap/gnome-3-34-1804-sdk/current/usr/bin/python3 isn't used and lxml module can be found
    ] 
    build-packages:
      - libgtksourceviewmm-3.0-dev # This is required as unfortunately not included with the gnome-3-34 extension.
                                   # However this will break the build as it includes older libglib2.0-dev 2.56
      - libxml++2.6-dev # required
      - libcpputest-dev # required
      - gcc-8 # See above
      - g++-8 # See above
      - python3-lxml # required